swagger: '2.0'
info:
  version: "1.0.0"
  title: Fetch Rewards Homework
  description: Email address parser homework assignment
host: 'localhost'
basePath: '/'
consumes:
  - application/json
produces:
  - application/json

paths:
  /email-checker:
    post:
      description: Returns a count of unique destination email addresses, following the gmail address filter rules. 
      parameters:
        - in: body
          schema:
            type: 
            properties:
              emails:
                description: An array of email addresses to parse
                type: array
                required: true
                example: ["test.email@gmail.com", "test.email+spam@gmail.com", "testemail@gmail.com"]
      responses:
        '200': 
          description: 200 ok with response
          schema:
            $ref: "#/definitions/response"
        '400': 
          description: 400 bad request with error object
          schema:
            $ref: "#/definitions/ErrorResponse"
  /healthcheck:
    get:
      description: Returns a 200 OK, with no response body. Used for monitoring purposes. 
      parameters:
      responses:
        '200': 
          description: 200 OK with response
definitions:
  Response:
    type: object
    example:
      {
        "unique_email_addresses": 1
      }
    properties:
      unique_email_addresses:
        type: int
        description: A list of the unique email destination addresses
  ErrorResponse:
    type: object
    example:
      {
        "code": 400,
        "error_message": "there was an error."
      }
    properties:
      code:
        type: int
        description: The http status code of the response
      error_message:
        type: string
        description: A summary of the error
